name: 'goods-web'
port: 8021
goods_srv:
  ip: '0.0.0.0'
  port: 50051 #这个东西用随机端口 直接通过名字进行服务发现
  name: 'goods_srv'
jwt:
  key:
    "TlqlNSqP?$pMLZ}GG{G`7/.R@!WQ4:(O"
consul:
  host: 'localhost'
  port: 8500


